name: Build HeriWRT x86_64

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build OpenWRT x86_64 - HeriWRT

    steps:
      - name: Checkout HeriWRT Source
        uses: actions/checkout@v3

      - name: Set up Dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
            gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
            python3-distutils rsync unzip zlib1g-dev file wget python3 \
            python3-pip python3-setuptools ccache libelf-dev libudev-dev

      - name: Clone OpenWRT Source
        run: |
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy Custom HeriWRT Files
        run: |
          mkdir -p openwrt/files/etc
          mkdir -p openwrt/files/www/luci-static/resources
          echo "Welcome to HeriWRT Firmware!" > openwrt/files/etc/banner
          cp ../heriWrt-logo-hd.png openwrt/files/www/luci-static/resources/

      - name: Config Build
        run: |
          cd openwrt
          make defconfig
          make menuconfig # You can automate this too with .config preset

      - name: Build Firmware
        run: |
          cd openwrt
          make -j$(nproc)

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v3
        with:
          name: HeriWRT-x86_64
          path: openwrt/bin/targets/
